MLShukai/PrimitiveAMI

pyproject.toml
#3 
PyTorchをインポート  
https://zenn.dev/zerebom/articles/b338784c8ac76a の手順で導入
=> pyproject.tomlにtorch関連の記述追加

src/models/components/action_predictor/action_predictor.py, src/models/components/action_predictor/continuous_action_predictor.py, src/models/components/action_predictor/discrete_action_predictor.py, src/models/components/inverse_dynamics/inverse_dynamics.py, src/models/components/observation_encoder/cnn_observation_encoder.py, src/models/components/observation_encoder/observation_encoder.py, tests/models/components/action_predictor/test_continuous_action_predictor.py, tests/models/components/inverse_dynamics/test_inverse_dynamics.py, tests/models/components/observation_encoder/test_cnn_observation_encoder.py
#2 InverseDynamicsの実装  
* InverseDynamics
* 抽象クラスActionPredictor
- 継承クラスContinuousActionPredictor
* 抽象クラスObservationEncoder
- 継承クラスCNNObservationEncoder
を追加
=> InverseDynamics実装

src/models/components/forward_dynamics/dense_net_forward_dynamics.py, src/models/components/forward_dynamics/forward_dynamics.py, tests/models/components/forward_dynamics/test_dense_net_forward_dynamics.py
https://github.com/MLShukai/PrimitiveAMI/issues/8  
抽象クラスForwardDynamicsとその継承DenseNetForwardDynamicsの実装
* ForwardDynamics
* DenseNetForwardDynamics
- のテスト
=> ForwardDynamicsとDenseNetForwardDynamicsとテスト追加

pyproject.toml, src/environment/interval_adjustor.py
#11 
feature番号間違えました...
IntervalAdjustorの実装です。adjustを具体クラスで実装します。
=> IntervalAdjustorの作成

src/environment/actuators/actuator.py, tests/environment/actuators/test_actuator.py
#14 
Actuatorの抽象クラスを追加。  
ドキュメント：https://www.notion.so/0d65a69ee5e44063a7f72dbc62c8ed84?pvs=4#3eb93883b53b4bf19415b640e39f0305
- `src/environment/actuators/actuator.py`
- `tests/environment/actuators/test_actuator.py`
=> Actuatorの抽象クラスの実装

src/environment/actuators/actuator.py
レビューに従って`Any`をアノテーションしましたが、importしてなかったのでエラーを吐いてしまいました。  
#33 
- `src/environment/actuators/actuator.py`
これに懲りて、もう `commit suggestion` は使いません。
=> Fix import

src/environment/sensors/sensor.py, tests/environment/sensors/test_sensor.py
#30 
Sensorの抽象クラスを追加。  
ドキュメント：https://www.notion.so/0d65a69ee5e44063a7f72dbc62c8ed84?pvs=4#b91d62e509ea4fc2b264fee2aa22984b
- `src/environment/sensors/sensor.py`
- `tests/environment/sensors/test_sensor.py`
=> Sensorの抽象クラス

src/environment/environment.py, tests/environment/test_environment.py
#28 
Environmentの抽象クラスを定義します。  
ドキュメント：https://www.notion.so/0d65a69ee5e44063a7f72dbc62c8ed84?pvs=4#dca866c62b3246dbade69273dfb642f0
以下ファイルを追加
- `src/environment/environment.py`
- `tests/environment/test_environment.py`
とりあえず`step`も使う前提で実装しました。
=> Environmentの抽象クラスの定義

pyproject.toml, src/environment/sensors/frame_sensor.py, tests/environment/sensors/test_frame_sensor.py
#35   
ドキュメント：https://www.notion.so/0d65a69ee5e44063a7f72dbc62c8ed84?pvs=4#c6d692e77bff4655833e8a4f649d324b
- `src/environment/sensors/frame_sensor.py`
- `tests/environment/sensors/test_frame_sensor.py`
こういうwarningが出ていますが、`cv2.VideoCapture`をパッチしている関係だと考えてスルーしています。  
まずそうなら教えてください。
=> FrameSensorの実装

pyproject.toml, src/environment/actuators/locomotion_actuator.py, tests/environment/actuators/test_locomotion_actuator.py
#38 
- `src/environment/actuators/locomotion_actuator.py`
- `tests/environment/actuators/test_locomotion_actuator.py`
github上のテストは device="cuda"が原因でパスしてないみたいです。ローカルでは作成したテストをすべてパスしていました。
=> LocomotionActuatorの実装

src/interactions/fixed_step_interaction.py, src/interactions/interaction.py, tests/interactions/test_fixed_step_interaction.py, tests/interactions/test_interaction.py
#41 Interaction抽象クラス及び決められた回数Interactionする `FixedStepInteraction`クラスを実装しました。
=> Interactionクラスを実装

src/environment/actuators/locomotion_actuator.py, src/environment/periodic_environment.py, tests/environment/actuators/test_locomotion_actuator.py, tests/environment/test_periodic_environment.py
#42 
Environmentの実装クラスPeriodicEnvironmentとそのテストを実装しました
=> PeriodicEnvironmentを実装

src/models/components/observation_encoder/cnn_observation_encoder.py, src/models/components/policy_value_common_net.py, src/models/components/small_conv_net.py, tests/models/components/test_policy_value_common_net.py, tests/models/components/test_small_conv_net.py
- SmallConvNetに`channels` 引数を指定しました。
- PolicyValueCommonNetの型アノテーションを追記しました。
=> SmallConvNetや一部Policyモデルの修正

src/agents/curiosity_ppo_agent.py, tests/agents/test_curisoity_ppo_agent.py
#45 CuriosityPPOAgentを実装し、一通りテストコードを書き終えました。張り切ってつくったらかなりオーバーエンジニアリングをしてしまったため、レビューが大変かもしれません... 次回からはもっと目的に沿ったレベルの実装にとどめます。
=> CuriosityPPOAgentを実装

demos/demo_agent_interaction.py, pyproject.toml, src/agents/curiosity_ppo_agent.py, src/data_collectors/empty_data_collector.py, src/environment/actuators/locomotion_actuator.py, src/interactions/fixed_step_interaction.py, src/models/components/observation_encoder/cnn_observation_encoder.py, src/utils/environment.py, src/utils/random.py, tests/dara_collectors/test_empty_data_collector.py, tests/utils/test_environment.py, tests/utils/test_random.py
#48  デモを動作させるためにいくつか修正をしています。
- ObservationEncoderにchannel数を指定できるようにしました。
- かっこいいログ出力をするためにColorlogを依存関係に追加しました。
- LocomotionActuator上でnumpy配列から値を取得するとOSC送信時にエラーが出たのでlist型に修正: 
エラー名: `ValueError: Infered arg_value type is not supported`
- LocomotionActuator, FrameSensorを簡単に呼び出すためのユーティリティ関数を追加
- その他、正常に動作するように修正
- Agent内部でObservationやActionにBatch軸を追加
=> Curiosity PPO Agentの推論動作demoを作成しました。

pyproject.toml
pytorch lightningを依存関係に追加しました。
https://lightning.ai/docs/pytorch/stable/
=> ADD dependency `lightning`

src/data_collectors/dummy_dynamics_data_collector.py, src/data_collectors/dynamics_data_collector.py, tests/dara_collectors/test_dummy_dynamics_data_collector.py, tests/dara_collectors/test_dynamics_data_collector.py
#52 
DynamicsDataCollector、DummyDynamicsDataCollector及びテスト追加
=> DynamicsDataCollectorの実装

src/models/ppo_lit_module.py, tests/models/test_ppo_lit_module.py
#55 
その後の実験などによって頻繁に変更が行われることが想定されるため、最小限のチェックとしています。
- データがエラーなく通過する
- "loss"が返される
=> PPOのLightningModuleを作成

src/data_collectors/dynamics_data_collector.py, tests/dara_collectors/test_dynamics_data_collector.py
https://github.com/MLShukai/PrimitiveAMI/pull/53#discussion_r1320726343  
https://github.com/MLShukai/PrimitiveAMI/pull/53#discussion_r1320726818  
に対する修正です
データ数がmax_sizeを超える場合の挙動修正
=> DynamicsDataCollectorがmax_size超える場合の処理修正

src/models/components/forward_dynamics/forward_dynamics_lit_module.py, src/trainers/forward_dynamics_trainer.py, tests/models/components/forward_dynamics/test_forward_dynamics_lit_module.py, tests/trainers/test_forward_dynamics_trainer.py
https://github.com/MLShukai/PrimitiveAMI/issues/61
ForwardDynamicsLitModuleとForwardDynamicsTrainerの実装
=> ForwardDynamicsTrainer実装

src/models/components/inverse_dynamics/inverse_dynamics_lit_module.py, src/trainers/inverse_dynamics_trainer.py, tests/trainers/test_inverse_dynamics_trainer.py
InverseDynamicsTrainerを実装しました。
#50 
LitModuleのブランチがマージ前なので、チェリーピックしました。
=> InverseDynamicsTrainerの実装

src/data_collectors/trajectory_data_collector.py, src/utils/step_record.py, tests/dara_collectors/test_trajectory_data_collector.py, tests/utils/test_step_record.py
https://github.com/MLShukai/PrimitiveAMI/issues/56
TrajectoryDataCollectorとテストの実装
next_valueって実行中に取れるんでしょうか？
=> TrajectoryDataCollector実装

src/data_collectors/trajectory_data_collector.py, src/models/ppo_lit_module.py, src/trainers/ppo_trainer.py, tests/dara_collectors/test_trajectory_data_collector.py, tests/trainers/test_ppo_trainer.py
https://github.com/MLShukai/PrimitiveAMI/issues/57
* TrajectoryDataCollectorのclearメソッドを忘れていたので実装
* PPOLitModuleのログ引数を修正
* PPOTrainerとテスト追加
=> PPOTrainer実装

src/models/ppo_lit_module.py
https://github.com/MLShukai/PrimitiveAMI/issues/72
設定可能な係数については調査したものをデフォルト値に設定  
あと何か設定必要なハイパラあります？
=> PPOLitModuleのclip_coef, clip_vloss, vfunc_coefを論文に合わせて設定

src/models/aggregations/neural_networks.py, tests/models/aggregations/test_neural_networks.py
=> NeuralNetworkの集約クラスの抽象クラス `NeuralNetworks`を実装しました。

src/models/aggregations/inverse_forward_ppo.py, tests/models/aggregations/test_inverse_forward_ppo.py
=> NeuralNetworksの実装 `InverseForwardPPO`クラスを実装しました。

src/trainers/builders/trainers_builder.py, tests/trainers/builders/test_trainers_builder.py
=> 抽象TrainersBuilderクラスを作成しました。

src/data_collectors/trajectory_data_collector.py
https://github.com/MLShukai/PrimitiveAMI/issues/90
`TrajectoryDataCollector`の`gamma`, `gae_lambda`のデフォルト値を設定
=> gammaとgae_lambdaのデフォルト値を設定

src/models/components/action_predictor/continuous_action_predictor.py, src/models/components/small_conv_net.py, tests/models/components/action_predictor/test_continuous_action_predictor.py, tests/models/components/test_small_conv_net.py
#80 
- `features_shared_with_policy`は反映していません。
- デフォルト値が`False`だったため
- 変更が大きくなりそうだったため
- 変更箇所には、根拠となる箇所のリンクを添付しています。
=> InverseDynamicsに関するデフォルトパラメータを設定しました

src/models/components/forward_dynamics/resnet_forward_dynamics.py, tests/models/components/forward_dynamics/test_resnet_forward_dynamics.py
https://github.com/MLShukai/PrimitiveAMI/issues/98
https://github.com/openai/large-scale-curiosity/blob/e0a698676d19307a095cd4ac1991c4e4e70e56fb/dynamics.py#L43-L65  
の実装に従いデフォルト4層のResNetとして実装
=> ResNetForwardDynamicsを実装

src/trainers/forward_dynamics_trainer.py, src/trainers/inverse_dynamics_trainer.py, src/trainers/ppo_trainer.py, src/trainers/simple_pl_trainer.py, tests/trainers/test_forward_dynamics_trainer.py, tests/trainers/test_inverse_dynamics_trainer.py, tests/trainers/test_ppo_trainer.py
https://github.com/MLShukai/PrimitiveAMI/pull/109
* ForwardDynamicsTrainer
* InverseDynamicsTrainer
* PPOTrainer
をSimplePLTrainerのエイリアスに置き換え
各テストを複数回train検証するよう修正
=> SimplePLTrainerの実装

src/data_collectors/obs_data_collector.py, src/data_collectors/vae_data_collector.py, tests/dara_collectors/test_vae_data_collector.py
`VAEDataCollector`を実装しました。  
step record から観測だけを取り出し、保存します。
=> VAEDataCollectorの実装

pyproject.toml, src/models/components/observation_encoder/vae.py, src/models/components/small_deconv_net.py, tests/models/components/observation_encoder/test_vae.py, tests/models/components/test_small_deconv_net.py
#92 #94 #95
以下を追加しました
- VAEのデコーダ用のクラス`SmallDeconvNet`
- `VAEEncoder`
- `VAEDecoder`
- `VAE`
- これらのテスト
=> VAEのコンポーネント作成

configs/agent/curiosity_ppo_agent.yaml, demos/demo_agent_interaction.py, pyproject.toml, src/agents/curiosity_ppo_agent.py, tests/agents/test_curisoity_ppo_agent.py, tests/config_tests/test_agent.py
#113 
- tensor board にもちゃんと記録されているようです。
=> Agentにloggerを追加し、Rewardの値を記録

configs/environment/frame_locomotion_sleep.yaml, configs/model/inverse_forward_ppo.yaml, tests/config_tests/test_model.py
#97 #99 の変更を取り込み、また画像サイズなどを調整してLarge Scale Curiosityと合わせました。
=> 原論文の実装に合うようにデフォルト値を修正

configs/train.yaml, src/train.py
`demos/demo_agent_learning.py`を`src/train.py`に変更し、適宜修正しました。
=> 学習のデモスクリプトを実験の実行ファイルとしてRenameしました。

configs/paths/default.yaml, configs/train.yaml, demos/demo_agent_interaction.py, src/agents/curiosity_ppo_agent.py, src/data_collectors/aggregations/dict_data_collectors.py, src/train.py, src/trainers/builders/trainers_builder.py, tests/agents/test_curisoity_ppo_agent.py
#111 の内容をtrain.pyに実装しました。先に #121 のレビューをお願いします。
=> データコレクタの状態保存機能をtrain.pyで用います。

configs/experiment/inverse_forward_ppo_from_checkpoint.yaml, configs/train.yaml, src/models/aggregations/inverse_forward_ppo.py
#111 #121 #122 をもとに、保存されたファイルから再開できる設定ファイルを追加しました。
=> 保存されたcheckpointやstate_dictファイルから再開できる設定ファイルの例を作りました。

configs/agent/random_agent.yaml, configs/random_interaction.yaml, src/agents/random_agent.py, src/random_interaction.py, tests/agents/test_random_agent.py, tests/config_tests/test_agent.py
=> ランダムに動作するAgentを作成しました。

configs/data_collector/dict_observation_dynamics_trajectory.yaml, configs/experiment/vae.yaml, configs/model/vae_forward_ppo.yaml, configs/trainers_builder/vae_forward_ppo.yaml, src/models/aggregations/vae_forward_ppo.py, src/models/components/observation_encoder/vae.py, src/models/vae_lit_module.py, src/trainers/builders/vae_forward_ppo.py, tests/config_tests/test_data_collector.py, tests/config_tests/test_model.py, tests/config_tests/test_trainers_builder.py, tests/models/components/observation_encoder/test_vae.py, tests/models/test_vae_lit_module.py
#132 python src/train.py experiment=vae で動きます。実験回します。
=> VAEをAMIに実装

tests/trainers/test_forward_dynamics_trainer.py
https://github.com/MLShukai/PrimitiveAMI/issues/139
`test_forward_dynamics_trainer.py`で作っている`pl.Trainer()`に`devices=1`を指定
恐らく実行時に他の箇所も修正が必要だがとりあえずテストが通るようにしたい
=> 使用デバイス数を1に制限

src/models/components/spiral_conv.py
https://github.com/MLShukai/PrimitiveAMI/issues/142
LightningのTrainerにより複素数パラメータが実数パラメータに変換されていたので最初から実数で持っておくことでエラーを回避
cfloatのパラメータをtorch.view_as_real()で実数パラメータに変換して保持し、使うときにtorch.view_as_complex()で戻す
=> SConvの複素数パラメータを実数で持つよう変更
